Upgrade to Fluent 1.3 and add Serializer test
qutheory/fluent-sqlite pull request #15
Opened 2017-01-10 16:27 UTC by Yasumoto

The `SQLiteSerializer` logic is likely already [well-tested](https://github.com/vapor/sqlite-driver/blob/master/Tests/FluentSQLiteTests/SQLiteDriverTests.swift#L67) so if y'all would prefer I delete the file (or have other feedback) please let me know!

I added the `exists` field following the deprecation warning:

```
[DEPRECATED] No 'exists' property is stored on 'Compound'. Add `var exists: Bool = false` to this model. The default implementation will be removed in a future update.
```

2017-01-10 22:13 UTC, loganwright requested changes
One stylistic tweak.

2017-01-10 22:13 UTC, LoganWright commented on Tests/FluentSQLiteTests/SQLiteSerializerTests.swift
> +    static var allTests: [(String, (SQLiteSerializerTests) -> () throws -> Void)] {
I prefer `static let allTests = [` and let inference do the work on the rest.

2017-01-11 02:43 UTC, Yasumoto commented on Tests/FluentSQLiteTests/SQLiteSerializerTests.swift
> +    static var allTests: [(String, (SQLiteSerializerTests) -> () throws -> Void)] {
Fixed up! Good call 👍

2017-01-11 17:59 UTC, loganwright approved these changes

2017-01-11 19:32 UTC, tanner0101 requested changes
Just one small thing. Otherwise, looks good to me.

2017-01-11 19:32 UTC, tannernelson commented on Package.swift
> +        .Package(url: "https://github.com/vapor/fluent.git", majorVersion: 1, minor: 3),
This should be changed to `majorVersion: 1` only for both. All internal dependencies should only specify major version. Looks like we missed this when we released the 1.0 tag.

2017-01-11 19:34 UTC, Yasumoto commented on Package.swift
> +        .Package(url: "https://github.com/vapor/fluent.git", majorVersion: 1, minor: 3),
Great call, done!

2017-01-12 00:02 UTC, tanner0101 approved these changes

2017-01-12 00:02 UTC, tannernelson commented
Thanks!

2017-01-12 00:02 UTC, merged